### ISSUE TITLE
POST: Overriding css declarations to achieve DRY

### ISSUE THREAD

**Issue by adammichaelwood** [adammichaelwood/hackwrite#9]
```css
.markdown h2:before,
.markdown h3:before,
.markdown h4:before,
.markdown h5:before,
.markdown h6:before {
  content: "## ";
  display: inline;
}
.markdown h3:before {
  content: "### ";
}
.markdown h4:before {
  content: "#### ";
}
.markdown h5:before {
  content: "##### ";
}
.markdown h6:before {
  content: "###### ";
}
```
